language: haskell

env:
  global:
    - "FTP_USER=user"
    - "FTP_PASSWORD=password"

install:
  - cabal install pandoc pandoc-citeproc

# command to generate all of the HTML docs
script: bash pandoc/travis_build.sh

after_success:
    "find pandoc \( ! -regex '.*/\..*' \) -type f -exec curl -u $FTP_USER:$FTP_PASSWORD --ftp-create-dirs -T {} ftp://ftp.siremol.org/devel/{} \;"
